### ISSUE TITLE
Contradiction in terms

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/programming-univbasics-2-introduction#3]
https://github.com/learn-co-curriculum/programming-univbasics-2-introduction/tree/wip-prework-v2.01#identify-the-nil-value-and-its-purpose

> The nil value means "no value." You might recall it is one of the falsey values in Ruby. It is the value that means "nothing." It's not true or false it's the void. It's not 3 and it's also not any other number.

You state that `nil` is falsey value but then continue on it is means "nothing".

**Comment by lizbur10** [comment]
Hello! I'm sorry to hear that the explanation was unclear! We have edited the content and believe your issue to be resolved. 

Thank you for contributing to the Flatiron curriculum!  💙
