### ISSUE TITLE
Copy Correction

### ISSUE THREAD

**Issue by m-delarosa** [learn-co-curriculum/programming-univbasics-2-introduction#4]
Typographical error found in copy: Introduction Section, P 2: "In writing we were expected to move from simple, one*-line answers to writing paragraphs."

**Comment by lizbur10** [comment]
Hello! I do not see this problem anywhere in the lesson's Readme so I'm closing this issue. If you believe there is still a problem please feel free to reopen this issue.

Thank you for submitting an issue and contributing to the Flatiron curriculum. 💙
